# window
width: 900
height: 600

# cloud
remote_server: [need_fill]
svn_username: [need_fill]
svn_password: [need_fill]

# feishu
notice_chat_id: oc_xxx
notice_base_url: xxx/vvrobot
notice_path: /hook/messages
notice_temp_id: ctp_xxx

# ssh
ssh_hostname: 172.31.30.32
ssh_username: root
ssh_password: root

# sdc sil server
sil_server_ip: 172.31.30.32
sil_server_port: 60000

# vcs
vcs_db_path: /app_data/vcs/
vcs_db_name: vcs_v1.db
vcs_signal_table_name: config_store_int

# local filepath
result_dir: data\result
ssh_key_filepath: data\key\xcu_rsa_ssh
idl_filepath: data\matrix\XBP.xml
dbo_filepath: data\matrix\dbc_lin_dbis_matrix.dbo
sil_local_filepath: data\key\sil
sil_sdf_local_filepath: data\key\sil.sdf
case_dir: data\case\debug

# remote filepath
sil_remote_filepath: /apps/x01/bin/sil
sil_sdf_remote_filepath: /apps/x01/sdf/sil.sdf
dbo_remote_filepath: /apps/x01/etc/sdc/dbc_lin_dbis_matrix.dbo

# dds
sub_topics:
  - ACSetStatus
  - BrakeSystemStatus

pub_topics:
  - ACSetStatus
